### ISSUE TITLE
The version number on master (1.12.1) is behind the one on R1_12_maintenance (1.12.2)

### ISSUE THREAD

**Issue by castortech** [eclipse/emf-validation#1]
## Description

Forked project to make a change and resulted build is at 1.12.1 instead of the official 1.12.2 that seems to originate from branch R1_12_maintenance that is not the master and seems to be behind.

**Comment by pcdavid** [comment]
`master` needs to be bumped to 1.13.0

**Comment by pcdavid** [comment]
Fixed by https://github.com/eclipse/emf-validation/commit/82645fe28eae58030cc9a7742282755b5077e3f3
